/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CounterComponent {
    }
    interface UserCard {
        /**
          * @default ''
         */
        "avatar": string;
        /**
          * @default 'john@example.com'
         */
        "email": string;
        /**
          * @default 'John Doe'
         */
        "name": string;
        /**
          * @default 'Developer'
         */
        "role": string;
    }
}
declare global {
    interface HTMLCounterComponentElement extends Components.CounterComponent, HTMLStencilElement {
    }
    var HTMLCounterComponentElement: {
        prototype: HTMLCounterComponentElement;
        new (): HTMLCounterComponentElement;
    };
    interface HTMLUserCardElement extends Components.UserCard, HTMLStencilElement {
    }
    var HTMLUserCardElement: {
        prototype: HTMLUserCardElement;
        new (): HTMLUserCardElement;
    };
    interface HTMLElementTagNameMap {
        "counter-component": HTMLCounterComponentElement;
        "user-card": HTMLUserCardElement;
    }
}
declare namespace LocalJSX {
    interface CounterComponent {
    }
    interface UserCard {
        /**
          * @default ''
         */
        "avatar"?: string;
        /**
          * @default 'john@example.com'
         */
        "email"?: string;
        /**
          * @default 'John Doe'
         */
        "name"?: string;
        /**
          * @default 'Developer'
         */
        "role"?: string;
    }
    interface IntrinsicElements {
        "counter-component": CounterComponent;
        "user-card": UserCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "counter-component": LocalJSX.CounterComponent & JSXBase.HTMLAttributes<HTMLCounterComponentElement>;
            "user-card": LocalJSX.UserCard & JSXBase.HTMLAttributes<HTMLUserCardElement>;
        }
    }
}
